settings:
  # mysql
  database:
    # 数据库类型 mysql，sqlite3， postgres
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    dsn: root:123456abc@tcp(127.0.0.1:3306)/chatroom?charset=utf8mb4&parseTime=true&loc=Local
    # 空闲连接池中连接的最大数量
    maxIdleConns: 10
    # 打开数据库连接的最大数量
    maxOpenConns: 100
    # 连接可复用的最大时间(秒)
    connMaxLifetime: 3600
    #默认是否关闭事务 关闭可大约 30%+ 性能提升
    skipDefaultTransaction: true
  # redis
  redis:
    # netWork
    netWork: tcp
    # pwd
    password:
    # 默认数据库 0 ～15
    dbSelect: 2
    # 最大空闲连接数
    maxIdle: 8
    # 表示和数据库大最大链接数，0表示不限制
    maxActive: 0
    # 最大空闲时间
    idleTimeout: 100
    # address
    address: 0.0.0.0:6379

  cookie:
    # 有效域
    path: /
    # 域名
    cookieDomain: 127.0.0.1:8060

    secure: false
    httpOnly: true